// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8HrIBZ7Z3pZ2T3vDyw2pgZXfMgASMFSQ',
    appId: '1:1000786214522:web:3596e37d992da2cbec05c3',
    messagingSenderId: '1000786214522',
    projectId: 'foodie-c1ddc',
    authDomain: 'foodie-c1ddc.firebaseapp.com',
    storageBucket: 'foodie-c1ddc.firebasestorage.app',
    measurementId: 'G-98D70Q69SS',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsmPieRIo1wEI-uTn11jI1BhaTJDQvG8Y',
    appId: '1:1000786214522:android:8fa495763ebb00d1ec05c3',
    messagingSenderId: '1000786214522',
    projectId: 'foodie-c1ddc',
    storageBucket: 'foodie-c1ddc.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiYVCqnV1m3uI6qUpz1yVF-lM-rT854y4',
    appId: '1:1000786214522:ios:7888d864d84d9be4ec05c3',
    messagingSenderId: '1000786214522',
    projectId: 'foodie-c1ddc',
    storageBucket: 'foodie-c1ddc.firebasestorage.app',
    iosBundleId: 'com.example.flutterFoodroute',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiYVCqnV1m3uI6qUpz1yVF-lM-rT854y4',
    appId: '1:1000786214522:ios:7888d864d84d9be4ec05c3',
    messagingSenderId: '1000786214522',
    projectId: 'foodie-c1ddc',
    storageBucket: 'foodie-c1ddc.firebasestorage.app',
    iosBundleId: 'com.example.flutterFoodroute',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8HrIBZ7Z3pZ2T3vDyw2pgZXfMgASMFSQ',
    appId: '1:1000786214522:web:1081643079faa533ec05c3',
    messagingSenderId: '1000786214522',
    projectId: 'foodie-c1ddc',
    authDomain: 'foodie-c1ddc.firebaseapp.com',
    storageBucket: 'foodie-c1ddc.firebasestorage.app',
    measurementId: 'G-00WCZP3SZ4',
  );
}
